### ISSUE TITLE
Feature wishlist

### ISSUE THREAD

**Issue by bjorn3** [oli-obk/priroda#5]
* [x] Alloc watching (#6)
* [x] Flame graph (cpu, memory) (#6) (reference for me: http://www.brendangregg.com/flamegraphs.html)
* [ ] Better representation of structs and enums. Also show field indexes/names and variant names. (partially by #8)
* [x] Optional auto refresh for pages (#4) (useful for testing priroda)
* [ ] Batch mode (useful for testing priroda)
* [ ] Edit allocs
* [ ] Better design
* [ ] Unit and integration tests
